version: "3.9"
services:
  validator:
    build:
      dockerfile: Dockerfile
      context: app/.
    env_file:
      - .env
    restart: unless-stopped
    expose:
      - "9090"
      - "1317"
      - "26656"
      - "26657"
    ports:
      - "9090:9090"
      - "1317:1317"
      - "26656:26656"
      - "26657:26657"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      default:
    volumes:
      - ./app/custom-entrypoint.sh:/opt/custom-entrypoint.sh
      - ./app/helpers.sh:/opt/helpers.sh
      - celestia-app:/root/.celestia-app
  bridge:
    image: ghcr.io/celestiaorg/celestia-node:0.6.0
    env_file:
      - .env
    environment:
      - NODE_TYPE=bridge
    restart: unless-stopped
    command: "celestia bridge start --core.ip $BRIDGE_CORE_IP --keyring.accname $BRIDGE_KEY_RING_ACC_NAME"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      default:
    volumes:
      - celestia-bridge-node:/root/.celestia-bridge-mocha
  light:
    image: ghcr.io/celestiaorg/celestia-node:0.6.1
    env_file:
      - .env
    environment:
      - NODE_TYPE=light
    restart: unless-stopped
    command: "celestia light start --core.ip $LIGHT_CORE_IP --keyring.accname $LIGHT_KEY_RING_ACC_NAME --gateway --gateway.addr 127.0.0.1 --gateway.port 26659 --p2p.network mocha"
    logging:
      options:
        max-size: "12m"
        max-file: "5"
    networks:
      default:
    volumes:
      - celestia-light-node:/root/.celestia-light-mocha
volumes:
  celestia-app:
  celestia-bridge-node:
  celestia-light-node:
networks:
  default:
